EXERCISE 10

(a) Write a program that transforms a given input matrix to upper Hessenberg form using Householder matrices.

In [290]:
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import math

In [291]:
A = np.array([[13,4,3,9],[-1,-8,5,0],[2,3,8,1],[6,-2,0,4]])
print(A)

[[13  4  3  9]
 [-1 -8  5  0]
 [ 2  3  8  1]
 [ 6 -2  0  4]]


Check the following two algorithms

In [292]:
def vhouse(x):
    n = len(x)
    x = x/np.linalg.norm(x,2)
    s = np.float(np.transpose(x[1:n])@x[1:n])
    v = np.array([[1]])
    v = np.append(v,x[1:n])   
    if s == 0:
        beta = 0
    else: 
        mu = math.sqrt(math.pow(x[0],2)+s)
        if x[0] <= 0:
            v[0] = x[0] - mu
        else:
            v[0] = (-s)/(x[0]+mu)
        beta = 2*math.pow(v[0],2)/(s+math.pow(v[0],2))
        v = v/v[0]
    return np.transpose(v), beta

In [293]:
v, beta = vhouse(np.array([-1,2,6]))
print(v)
print(beta)

[ 1.         -0.27015621 -0.81046864]
1.156173761888606


/var/folders/1z/q6prr8vx16186b_fkgsq8fcw0000gp/T/ipykernel_25101/2049448725.py:4: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  s = np.float(np.transpose(x[1:n])@x[1:n])


In [294]:
def houshess(A):
    n = max(np.shape(A))
    Q = np.identity(n)
    H = A.copy()
    for k in range(n-2):
        v, beta = vhouse(H[(k+1):n,k])
        #print(v,beta)
        v = v[:,np.newaxis]
        I = np.identity(k+1)
        N = np.zeros((k+1,n-(k+1)))
        m = len(v)
        #print(beta*v@np.transpose(v))
        R = np.identity(m) - beta*v@np.transpose(v)
        #print(R)
        #print(v)
        print(R@H[(k+1):n,k:n])
        H[(k+1):n,k:n] = R@H[(k+1):n,k:n]
        print(H[(k+1):n,k:n])
        H[0:n,(k+1):n] = H[0:n,(k+1):n]@R
        P = np.block([[I,N],[np.transpose(N),R]])
        Q = Q@P

    return H, Q


In [295]:
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
h, q = houshess(C)
#print(h)

[[8.06225775e+00 9.42663983e+00 1.07910219e+01]
 [8.88178420e-16 3.72104204e-01 7.44208408e-01]]
[[ 8  9 10]
 [ 0  0  0]]


/var/folders/1z/q6prr8vx16186b_fkgsq8fcw0000gp/T/ipykernel_25101/2049448725.py:4: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  s = np.float(np.transpose(x[1:n])@x[1:n])


In [296]:
H, Q = houshess(A)
print(np.transpose(Q)@A@Q)
print(H)

[[ 6.40312424e+00  3.12347524e-01  1.71791138e+00  4.06051781e+00]
 [ 0.00000000e+00  7.54367681e-01  8.88667663e+00 -9.69741095e-02]
 [ 1.55431223e-15 -8.73689696e+00  2.66002989e+00  7.09077671e-01]]
[[ 6  0  1  4]
 [ 0  0  8  0]
 [ 0 -8  2  0]]
[[ 2.23606798e+00  6.26099034e+00 -5.36656315e+00]
 [-1.11022302e-16  3.13049517e+00  6.26099034e+00]]
[[ 2  6 -5]
 [ 0  3  6]]
[[ 1.30000000e+01  8.74573067e+00  3.84136663e+00 -3.84136663e+00]
 [ 6.40312424e+00  4.29268293e+00  9.47993943e-01 -4.59092736e-01]
 [ 1.11022302e-15  3.57496468e+00  4.16405436e+00  7.99294963e+00]
 [-1.33226763e-15 -1.40983076e+00  6.89973330e+00 -4.45673729e+00]]
[[13  8  3 -4]
 [ 6  4  0  0]
 [ 0  2  3  7]
 [ 0  0  5 -4]]


/var/folders/1z/q6prr8vx16186b_fkgsq8fcw0000gp/T/ipykernel_25101/2049448725.py:4: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  s = np.float(np.transpose(x[1:n])@x[1:n])


In [297]:
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
h, q = houshess(C)
print(h)

[[8.06225775e+00 9.42663983e+00 1.07910219e+01]
 [8.88178420e-16 3.72104204e-01 7.44208408e-01]]
[[ 8  9 10]
 [ 0  0  0]]
[[ 1  3  0]
 [ 8 13  2]
 [ 0  0  0]]


/var/folders/1z/q6prr8vx16186b_fkgsq8fcw0000gp/T/ipykernel_25101/2049448725.py:4: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  s = np.float(np.transpose(x[1:n])@x[1:n])


In [298]:
def householder(A):
    (n,m)=A.shape
    p=min(n,m)
    alpha=np.zeros(m)
    for j in range(0,p):
        alpha[j]=np.linalg.norm(A[j:,j])*np.sign(A[j,j])
        if (alpha[j]!=0):
            beta=1/math.sqrt(2*alpha[j]*(alpha[j]+A[j,j]))
            A[j,j]=beta*(A[j,j]+alpha[j])
            A[j+1:,j]=beta*A[j+1:,j]
            for k in range(j+1,m):
                gamma=2*A[j:,j].dot(A[j:,k])
                A[j:,k]=A[j:,k]-gamma*A[j:,j]
    return A,alpha

In [299]:
  b, a = householder(A)
print(b)

[[ 0  4  3  9]
 [ 0  0  5  0]
 [ 0  0  1 -1]
 [ 0  0  0  1]]
