EXERCISE 10

(a) Write a program that transforms a given input matrix to upper Hessenberg form using Householder matrices.

In [172]:
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import math

In [173]:
A = np.array([[float(13),float(4),float(3),float(9)],
              [float(-1),float(-8),float(5),float(0)],
              [float(2),float(3),float(8),float(1)],
              [float(6),float(-2),float(0),float(4)]])
print(A)

[[13.  4.  3.  9.]
 [-1. -8.  5.  0.]
 [ 2.  3.  8.  1.]
 [ 6. -2.  0.  4.]]


Check the following two algorithms

In [174]:
def vhouse(x):
    n = len(x)
    x = x/np.linalg.norm(x,2)
    s = float(np.transpose(x[1:n])@x[1:n])
    v = np.array([[1]])
    v = np.append(v,x[1:n])   
    if s == 0:
        beta = 0
    else: 
        mu = math.sqrt(math.pow(x[0],2)+s)
        if x[0] <= 0:
            v[0] = x[0] - mu
        else:
            v[0] = (-s)/(x[0]+mu)
        beta = 2*math.pow(v[0],2)/(s+math.pow(v[0],2))
        v = v/v[0]
    return np.transpose(v), beta

In [175]:
def houshess(A):
    n = max(np.shape(A))
    Q = np.identity(n)
    H = A.copy()
    for k in range(n-2):
        v, beta = vhouse(H[(k+1):n,k])
        #print(v,beta)
        v = v[:,np.newaxis]
        I = np.identity(k+1)
        N = np.zeros((k+1,n-(k+1)))
        m = len(v)
        #print(beta*v@np.transpose(v))
        R = np.identity(m) - beta*v@np.transpose(v)
        #print(R)
        #print(v)
        #print(R@H[(k+1):n,k:n])
        H[(k+1):n,k:n] = R@H[(k+1):n,k:n]    #star
        H[0:n,(k+1):n] = H[0:n,(k+1):n]@R
        P = np.block([[I,N],[np.transpose(N),R]])
        Q = Q@P

    return H, Q

In [176]:
H, Q = houshess(A)
print(Q@H@np.transpose(Q)-A)
print(np.transpose(Q)-np.linalg.inv(Q))
print(H)

[[ 0.00000000e+00 -8.88178420e-16  1.77635684e-15 -1.77635684e-15]
 [-8.88178420e-16  7.10542736e-15  0.00000000e+00  0.00000000e+00]
 [ 1.33226763e-15  0.00000000e+00  0.00000000e+00  8.88178420e-16]
 [-1.77635684e-15  4.44089210e-16 -3.33066907e-16 -2.22044605e-15]]
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.66533454e-16 -5.55111512e-17  0.00000000e+00]
 [ 0.00000000e+00 -2.22044605e-16  1.66533454e-16  4.33680869e-17]
 [ 0.00000000e+00  3.33066907e-16 -2.22044605e-16  5.55111512e-17]]
[[ 1.30000000e+01  8.74573067e+00  4.98278706e+00 -2.16426158e+00]
 [ 6.40312424e+00  4.29268293e+00  1.05031935e+00 -7.92963925e-02]
 [ 0.00000000e+00  3.84291494e+00 -2.07886621e+00  8.93069199e+00]
 [ 1.55431223e-15  4.44089210e-16  7.83747565e+00  1.78618328e+00]]


H is upper Hessenberg and Q is orthogonal. Also it holds that Q^T@A@Q=H.

In [177]:
B = np.array([[float(4),float(3),float(2),float(1)],
              [float(3),float(4),float(3),float(2)],
              [float(2),float(3),float(4),float(3)],
              [float(1),float(2),float(3),float(4)]])
print(B)

[[4. 3. 2. 1.]
 [3. 4. 3. 2.]
 [2. 3. 4. 3.]
 [1. 2. 3. 4.]]


In [178]:
Hb, Qb = houshess(B)
print(Qb@Hb@np.transpose(Qb)-B)
print(np.transpose(Qb)-np.linalg.inv(Qb))
print(Hb)

[[ 0.00000000e+00 -8.88178420e-16 -2.22044605e-16 -1.11022302e-16]
 [-8.88178420e-16 -8.88178420e-16 -4.44089210e-16  0.00000000e+00]
 [-2.22044605e-16 -8.88178420e-16 -4.44089210e-16 -4.44089210e-16]
 [-1.11022302e-16 -2.22044605e-16  0.00000000e+00  8.88178420e-16]]
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -1.11022302e-16 -1.11022302e-16  1.11022302e-16]
 [ 0.00000000e+00  5.55111512e-17  0.00000000e+00  1.11022302e-16]
 [ 0.00000000e+00 -5.55111512e-17  1.11022302e-16  0.00000000e+00]]
[[4.00000000e+00 3.74165739e+00 0.00000000e+00 0.00000000e+00]
 [3.74165739e+00 8.28571429e+00 2.60298102e+00 0.00000000e+00]
 [0.00000000e+00 2.60298102e+00 3.03958692e+00 2.25401047e-01]
 [0.00000000e+00 5.55111512e-17 2.25401047e-01 6.74698795e-01]]


The matrix B is symmetric and the householder transformation maintains that property. This means that (as observed) Hb is symmetric as well and tridiagonal. The algorithm can be adapted to this problem by simplifying the matrix multiplication #star by only calculating the upper (or lower) part of the matrix and then simply flipping the matrix as each of the iterations is symmetric again. This saves computational cost through the matrix multiplication.